crud update
learn-co-curriculum/phase-4-project-guidelines pull request #11
Opened 2023-04-11 17:21 UTC by charneff

2023-04-11 22:06 UTC, lizbur10 requested changes
Hi Charlotte! Sorry this slipped through the cracks earlier :)

Doing the line by line suggestions got a little unwieldy so I might have screwed something up. Please check it!

2023-04-11 22:06 UTC, lizbur10 commented on README.md
> +in the backend of the project. Simply altering the front end to hide the edit & delete
```suggestion
in the back end of the project. Simply altering the front end to hide the edit & delete 
```

2023-04-11 22:06 UTC, lizbur10 commented on README.md
> +looks something like this `if current_user.id == post.user.id` assuming you have a
```suggestion
looks something like this: `if current_user.id == post.user.id`.
```

2023-04-11 22:06 UTC, lizbur10 commented on README.md
> +buttons is insufficient in terms of security. The code needed to secure these operations
```suggestion
buttons is insufficient in terms of security. Assuming you have a `current_user` method and a post belongs to a user, the code needed to secure these operations
```

2023-04-11 22:06 UTC, lizbur10 commented on README.md
> +current user method and a post belongs to a user. Alternatively, the most performant way
```suggestion
Alternatively, the most performant way
```

2023-04-11 22:06 UTC, lizbur10 commented on README.md
> +to implement this is `post = current_user.posts.find(params[:id])` with an if statement
```suggestion
to implement this is:
```

2023-04-11 22:06 UTC, lizbur10 commented on README.md
> +starting on the next line `if post` do something, `else` do something else.
```suggestion

```

2023-04-11 22:06 UTC, lizbur10 commented on README.md
```ruby
 post = current_user.posts.find(params[:id])
if post
  <do something>
else
  <do something else>
end
```

2023-04-12 13:26 UTC, charneff commented on README.md
I think I got this added properly ;)

2023-04-12 13:50 UTC, lizbur10 approved these changes
Looks good!

2023-04-12 13:50 UTC, merged