update
learn-co-curriculum/phase-4-project-guidelines pull request #8
Opened 2022-09-20 23:50 UTC by charneff

Duplicative language around has many/belongs ro removed. This was confusing students. Added in restful routing and proper state updating. Also added in validations and error messaging.

2022-10-04 15:30 UTC, lizbur10 reviewed
I think we need to hold off on merging this one in for a week or two. I'll need to get `useContext` out of the optional module before this goes live. There's also the Heroku issue - they have announced a student option and we're looking into whether that's going to work for us. In the meantime, it's fine to make the edit on lines 207-208 for current cohorts.

2022-10-07 15:32 UTC, charneff commented
Gotcha,. That is totally fine. Whenever updated to required, would love to add in useContext =)

2023-02-07 16:51 UTC, lizbur10 requested changes
Hi @charneff! So sorry this slipped through the cracks!!

I've requested a couple of corrections then I think we can merge it in

2023-02-07 16:51 UTC, lizbur10 commented on README.md
> +  end and displayed if the action fails. HINT: Utilize `record.errors`.
Correction: "...and display them if ..."

2023-02-07 16:51 UTC, lizbur10 commented on README.md
This change needs to be undone. All that needs to change is Heroku -> Render

2023-02-07 17:11 UTC, lizbur10 approved these changes

2023-02-07 17:12 UTC, merged